[theme]
base = "dark"
primaryColor = "#10B981"
backgroundColor = "#080D1A"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
